# Generated by Django 4.1.13 on 2024-03-14 09:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=30)),
                ('content_type', models.CharField(default='none', max_length=10)),
                ('storage_path', models.CharField(max_length=225)),
                ('url', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'File',
            },
        ),
    ]
