# Generated by Django 4.1.13 on 2024-03-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Document',
        ),
    ]
