# Generated by Django 4.1.13 on 2024-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size', models.IntegerField(default=0)),
                ('content_type', models.CharField(default='none', max_length=5)),
                ('storage_path', models.CharField(max_length=225)),
                ('url', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'ImageMetadata',
            },
        ),
    ]
